name: Test Infrastructure Setup

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 1,16 * *'
  workflow_dispatch:

jobs:
  test-dotfiles:
    runs-on: macos-latest  # Use the latest macOS runner

    steps:
      - name: ğŸ“¥ Checkout Repository
        uses: actions/checkout@v4

      - name: Start Docker
        run: |
          brew install --cask docker
          open -a Docker
          sleep 10
          docker info

      - name: ğŸ”§ Set up Docker
        run: |
          brew install docker-compose
          docker-compose --version

      - name: ğŸ› ï¸set up Makefile
        run: |
          brew install make

      - name: ğŸ’» Run dotfiles installer
        run: |
          chmod +x ./elk/filebeat.yml
          chmod +x ./elk/metricbeat.yml

      - name: âœ… Run and Verify SonarQube
        run: |
          make sonar-up